### ISSUE TITLE
Security issue: the bundle make any file readable / deletable

### ISSUE THREAD

**Issue by nreynis** [greenskies/WebLogViewerBundle#4]
The `LogViewerController` log parameter accepts parent (upward) navigation.
This make probing the filesystem and viewing any file (even php files) a breeze:

```
http://unsecureapp.com/logs/viewer?log=../../app/config/parameters.yml
```
You should validate that the requested file is within the configured log directory before displaying or deleting it.

**Comment by eidsonator** [comment]
Thanks!  Merged your fix and bumped the patch number.
